### PR TITLE
Update release.yml to use v1 upload action

### PR DESCRIPTION
**Pull request by thehomebrewnerd**
- Updates `release.yml` to use `v1` of `gh-action-pypi-upload` instead of installing from `master`.
- Ignore .DS_Store files in .gitignore

### CODE REVIEW

**Review by gsheni — APPROVED** [review]

**Comment by gsheni** [comment]
@thehomebrewnerd for the Featuretools python 3.10 support, we did not have to make changes, and there are no restrictions on Featuretools to prevent 3.10 usage:
https://github.com/alteryx/featuretools/pull/1940
So do we actually need to wait for Featuretools to support 3.10?

**Comment by thehomebrewnerd** [comment]
> @thehomebrewnerd for the Featuretools python 3.10 support, we did not have to make changes, and there are no restrictions on Featuretools to prevent 3.10 usage: [alteryx/featuretools#1940](https://github.com/alteryx/featuretools/pull/1940) So do we actually need to wait for Featuretools to support 3.10?

@gsheni I'll take a closer look. Maybe something else is causing the CI test failures.

**Comment by thehomebrewnerd** [comment]
> @thehomebrewnerd for the Featuretools python 3.10 support, we did not have to make changes, and there are no restrictions on Featuretools to prevent 3.10 usage: [alteryx/featuretools#1940](https://github.com/alteryx/featuretools/pull/1940) So do we actually need to wait for Featuretools to support 3.10?

I think the issue might actually be with tsfresh or one of its dependencies. For now, I think I'll revert the Python 3.10 changes, and create a new issue to look into it further as a separate issue.

**Comment by thehomebrewnerd** [comment]
@gsheni Well, now unfortunately things are broken with because the latest release of Woodwork a few minutes ago contains a breaking change that has not yet been fixed in Featuretools, so we will now once again need to wait for the next release of Featuretools.

**Comment by thehomebrewnerd** [comment]
Will add Python 3.10 support in a separate PR: #95

**Review by gsheni — APPROVED** [review]

**Pull request merged**
